services:
  app:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_DB: todos
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    volumes:
      - ./:/app

  db:
    image: mysql:8.0
    restart: always
    user: root
    secrets:
      - db-password
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  todo-mysql-data:

secrets:
  db-password:
    file: db/password.txt